### ISSUE TITLE
File not found:  SiqiLu/dotnet-bump-version/master/lib/main.js'

### ISSUE THREAD

**Issue by sellingsolutions** [SiqiLu/dotnet-bump-version#1]
Run SiqiLu/dotnet-bump-version@master
  with:
    version_files: **/*.csproj
    github_token: ***
  env:
    DOTNET_ROOT: /opt/hostedtoolcache/dncs/3.1.100/x64
##[error]File not found: '/home/runner/work/_actions/SiqiLu/dotnet-bump-version/master/lib/main.js'

**Comment by SiqiLu** [comment]
The reason is that file names on linux are case sensitive. 
Fixed.
Please have a try.
