### ISSUE TITLE
How to bump a major, minor or patch

### ISSUE THREAD

**Issue by MortenMeisler** [SiqiLu/dotnet-bump-version#13]
Seems like it only works if you have 4 numbers in your version, so updating nuget does not work etc.

This works:
```<Version>1.0.0.2</Version>```

This does not work:
```<Version>1.0.2</Version>```

I can see in the code there is some optionsRex with --patch, but how does it work?

**Comment by SiqiLu** [comment]
When you submit a commit, if the commit message contains "--build", the action will bump the build part of the version number;
If the commit message contains "--patch", the action will bump the patch part of the version number;
If the commit message contains "--minor", the action will bump the minor part of the version number;
If the commit message contains "--major", the action will bump the major part of the version number.

My suggestion is that you can use the 2.0.0 version of the action directly, you can use the version_mask in the Input options to control the version part you want to bump.
