### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'toString')

### ISSUE THREAD

**Issue by madnik7** [SiqiLu/dotnet-bump-version#22]
It was working before in another project, not sure what I did but I keep getting the following error now:
Error: Cannot read properties of undefined (reading 'toString')
https://github.com/graymint/GrayMint.Common/actions/runs/3179014040/jobs/5181072363

Any resolution?

**Comment by madnik7** [comment]
I noticed that there is no error if I change something and commit in GitHub web UI but this error raises if I push my project from local.

**Comment by madnik7** [comment]
Hi, Have you seen this bug? Is this project active?

**Comment by SiqiLu** [comment]
Yes, I am still here. But I cannot see the logs from the above link. Please send another action logs.

**Comment by SiqiLu** [comment]
> I noticed that there is no error if I change something and commit in GitHub web UI but this error raises if I push my project from local.

That sounds very strange.

**Comment by SiqiLu** [comment]
It might have something to do with your options of the git command. The GitHub web UI use the different options with your local git command, this is a common situation.
Anyway, please send me the error log for reference first so I can locate the problem faster.

**Comment by madnik7** [comment]
Thank you for replying:
Here is the log; GitHub will delete it after a day:
https://github.com/graymint/GrayMint.Common/actions/runs/3215428362/jobs/5256518097

I use Visual Studio to commit and push the commits.
It worked before, and I have to say this is a great add-on, but unfortunately, it doesn't work as before.
It works If I change something online and save it, but it doesn't work with Visual Studio push.

**Comment by SiqiLu** [comment]
I follow the steps:
1. fork the repository of "GrayMint.Common".
2. git clone to my local machine.
3. changed some files in the dev branch.
4. commit and merge to main branch.
5. push the main branch to github.

Then, the action run and succeed.
Here is the log:
https://github.com/SiqiLu/GrayMint.Common/actions/runs/3218051532/jobs/5261752412

So, for resolving the problem. Could you please run the action in your repository, and when the action fail, please click the button "Re-run jobs", and then click the button "re-run failed jobs", and then check the box "Enable debug logging", rerun the jobs. I have some screenshots below, you can follow the steps to rerun the jobs.

And send me the logging link with the debug logging.

![image](https://user-images.githubusercontent.com/3321644/194832423-bdb25896-c76c-4532-8d2a-790f196077ad.png)
![image](https://user-images.githubusercontent.com/3321644/194832662-374f4819-811b-4369-8074-64b8e414fc79.png)

**Comment by madnik7** [comment]
I re-runed the job with debugging logging and here is the result:
https://github.com/graymint/GrayMint.Common/actions/runs/3215428362/jobs/5285155139

**Comment by madnik7** [comment]
I also did the same, forked it into my personal repo, cloned, changed, and commit. But it doesn't work for me:

Here is the result with debug loggin
https://github.com/madnik7/GrayMint.Common/actions/runs/3228768653/jobs/5285320930

Any idea?

**Comment by SiqiLu** [comment]
Did you cloned the code to your local machine?

**Comment by SiqiLu** [comment]
Did it work if you change the file with the github website and commit with the web UI?

**Comment by SiqiLu** [comment]
Also, what I want to know is what encoding is your code file on your local machine? "UTF8" or "ASNI"?

**Comment by madnik7** [comment]
> Did you clone the code to your local machine?
yes

> Did it work if you change the file with the GitHub website and commit with the web UI?
Yes

> Also, what I want to know is what encoding is your code file on your local machine. "UTF8" or "ASNI"?
Which files? csproj are ANSI

**Comment by SiqiLu** [comment]
Please try the 2.0.1 version action by modifying the action configuration of file"/.github/workflows/nuget.yml"  from "SiqiLu/dotnet-bump-version@2.0.0" to "SiqiLu/dotnet-bump-version@2.0.1-donotuse" in line 21.

**Comment by madnik7** [comment]
> Please try the 2.0.1 version action by modifying the action configuration of file"/.github/workflows/nuget.yml" from "SiqiLu/dotnet-bump-version@2.0.0" to "SiqiLu/[dotnet-bump-version@2.0.1-donotuse](mailto:dotnet-bump-version@2.0.1-donotuse)" in line 21.

Same error:
https://github.com/graymint/GrayMint.Common/actions/runs/3240679682/jobs/5311614006

**Comment by madnik7** [comment]
Could you find the issue or have any idea how can I solve it?

**Comment by madnik7** [comment]
I sort it out after more than 30 tries and errors. Believe it or not, if  I tell you, it didn't work because I set the email in c:\Users\.gitconfig to developer@google.com, and any other email works! I even don't use global config for my repo! I couldn't believe it unless and change it many times to confirm that it was the issue. 

![image](https://user-images.githubusercontent.com/3189803/199109871-417cd4b7-3943-413b-92ca-7acf3360981c.png)

**Comment by TomKirby** [comment]
I Understand this issue is closed, but I too ran into the same problem, I updated my Git Email Address (Which was originally set to a different email address than the one I used to log into Github with) to an email address matching the one I use to log into github and it seems to now be working ok.

I do specify `github_token: ${{ secrets.GITHUB_TOKEN }}` so maybe it has something to do with a malalignment of user details from the original commit to the commit the Version bump is performing?
