### ISSUE TITLE
bump VersionSuffix

### ISSUE THREAD

**Issue by trudyhood** [SiqiLu/dotnet-bump-version#25]
I am not sure if this project is active or not. You have already bumped PackageVersion, AssemblyVersion,FileVersion and InformationalVersion . 

Can you bump VersionSuffix too?

**Comment by SiqiLu** [comment]
Can you give an example to describe your needs?

**Comment by trudyhood** [comment]
Thank you for your reply. I have forgotten why I needed it that time.
