### ISSUE TITLE
Only commit updated project files

### ISSUE THREAD

**Issue by TheConstructor** [SiqiLu/dotnet-bump-version#5]
Currently you use
https://github.com/SiqiLu/dotnet-bump-version/blob/16e4f1d83e9d5811bbd269e786e98a941ea0a64b/src/Commit.ts#L27
which will result in all files being added to the next commit. If e.g. your build creates any e.g. coverage-report and you did not correctly add it to `.gitignore`, they are committed as well.

As you already have the project-files as argument to the action it would probably be a good idea to add just the files specified there.

**Comment by SiqiLu** [comment]
Yes, it's a bug. Could you please fix this and create a pull request?
